import { DarkTheme, DefaultTheme, type Theme } from 'expo-router/react-navigation';

/** Brand-mapped tokens mirroring global.css / constants/theme.ts */
export const THEME = {
  light: {
    background: '#F8FAFC',
    foreground: '#0F172A',
    card: '#FFFFFF',
    cardForeground: '#0F172A',
    popover: '#FFFFFF',
    popoverForeground: '#0F172A',
    primary: '#2563EB',
    primaryForeground: '#FFFFFF',
    secondary: '#F1F5F9',
    secondaryForeground: '#0F172A',
    muted: '#F1F5F9',
    mutedForeground: '#64748B',
    accent: '#DBEAFE',
    accentForeground: '#1E40AF',
    destructive: '#EF4444',
    border: '#E2E8F0',
    input: '#E2E8F0',
    ring: '#2563EB',
    radius: '0.75rem',
    chart1: '#2563EB',
    chart2: '#10B981',
    chart3: '#F59E0B',
    chart4: '#8B5CF6',
    chart5: '#EF4444',
  },
  dark: {
    background: '#000000',
    foreground: '#FFFFFF',
    card: '#121212',
    cardForeground: '#FFFFFF',
    popover: '#121212',
    popoverForeground: '#FFFFFF',
    primary: '#2563EB',
    primaryForeground: '#FFFFFF',
    secondary: '#1C1C1E',
    secondaryForeground: '#FFFFFF',
    muted: '#1C1C1E',
    mutedForeground: '#9CA3AF',
    accent: '#1E3A8A',
    accentForeground: '#DBEAFE',
    destructive: '#EF4444',
    border: '#2A2A2C',
    input: '#2A2A2C',
    ring: '#2563EB',
    radius: '0.75rem',
    chart1: '#3B82F6',
    chart2: '#10B981',
    chart3: '#F59E0B',
    chart4: '#8B5CF6',
    chart5: '#EF4444',
  },
} as const;

export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};
